server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  h2:
    console.enabled: true
  application:
    name: find_talent
  datasource:
      url: jdbc:h2:mem:mydb
      username: sa
      password: password
      driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    generate-ddl: true


logging:
  level:
    org.springframework.web: info
    org.hibernate: error
  pattern:
    console: "%cyan(%d{yyyy-MM-dd HH:mm:ss}) [%green(%thread)] %highlight(%-5level) %yellow(%logger{36}) - %msg%n"